// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO customers (id, email_hash, email_encrypted, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCustomerParams struct {
	ID             uuid.UUID
	EmailHash      []byte
	EmailEncrypted []byte
	PasswordHash   string
	CreatedAt      time.Time
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.Exec(ctx, createCustomer,
		arg.ID,
		arg.EmailHash,
		arg.EmailEncrypted,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const getCustomerByEmailHash = `-- name: GetCustomerByEmailHash :one
SELECT id, email_hash, email_encrypted, password_hash, created_at FROM customers WHERE email_hash = $1
`

func (q *Queries) GetCustomerByEmailHash(ctx context.Context, emailHash []byte) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmailHash, emailHash)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEncrypted,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, email_hash, email_encrypted, password_hash, created_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEncrypted,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
