// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMerchant = `-- name: CreateMerchant :exec
INSERT INTO merchants (id, email_hash, email_encrypted, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMerchantParams struct {
	ID             uuid.UUID
	EmailHash      []byte
	EmailEncrypted []byte
	PasswordHash   string
	CreatedAt      time.Time
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) error {
	_, err := q.db.Exec(ctx, createMerchant,
		arg.ID,
		arg.EmailHash,
		arg.EmailEncrypted,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const getMerchantByEmailHash = `-- name: GetMerchantByEmailHash :one
SELECT id, email_hash, email_encrypted, password_hash, created_at FROM merchants WHERE email_hash = $1
`

func (q *Queries) GetMerchantByEmailHash(ctx context.Context, emailHash []byte) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByEmailHash, emailHash)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEncrypted,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, email_hash, email_encrypted, password_hash, created_at FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEncrypted,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
