// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PetSpecies string

const (
	PetSpeciesCAT  PetSpecies = "CAT"
	PetSpeciesDOG  PetSpecies = "DOG"
	PetSpeciesFROG PetSpecies = "FROG"
)

func (e *PetSpecies) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetSpecies(s)
	case string:
		*e = PetSpecies(s)
	default:
		return fmt.Errorf("unsupported scan type for PetSpecies: %T", src)
	}
	return nil
}

type NullPetSpecies struct {
	PetSpecies PetSpecies
	Valid      bool // Valid is true if PetSpecies is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetSpecies) Scan(value interface{}) error {
	if value == nil {
		ns.PetSpecies, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetSpecies.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetSpecies) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetSpecies), nil
}

type PetStatus string

const (
	PetStatusAVAILABLE PetStatus = "AVAILABLE"
	PetStatusSOLD      PetStatus = "SOLD"
	PetStatusREMOVED   PetStatus = "REMOVED"
)

func (e *PetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetStatus(s)
	case string:
		*e = PetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PetStatus: %T", src)
	}
	return nil
}

type NullPetStatus struct {
	PetStatus PetStatus
	Valid     bool // Valid is true if PetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetStatus), nil
}

type Customer struct {
	ID             uuid.UUID
	EmailHash      []byte
	EmailEncrypted []byte
	PasswordHash   string
	CreatedAt      time.Time
}

type Merchant struct {
	ID             uuid.UUID
	EmailHash      []byte
	EmailEncrypted []byte
	PasswordHash   string
	CreatedAt      time.Time
}

type Pet struct {
	ID                    uuid.UUID
	StoreID               uuid.UUID
	Name                  string
	Species               string
	AgeYears              int32
	Description           string
	BreederNameEncrypted  []byte
	BreederEmailEncrypted []byte
	PictureObjectKey      string
	Status                string
	CreatedAt             time.Time
	SoldAt                pgtype.Timestamptz
	SoldByCustomerID      pgtype.UUID
	RemovedAt             pgtype.Timestamptz
}

type Store struct {
	ID         uuid.UUID
	MerchantID uuid.UUID
	Name       string
	CreatedAt  time.Time
}
