// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pets.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPet = `-- name: CreatePet :exec
INSERT INTO pets (
    id, store_id, name, species, age_years, description,
    breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreatePetParams struct {
	ID                    uuid.UUID
	StoreID               uuid.UUID
	Name                  string
	Species               string
	AgeYears              int32
	Description           string
	BreederNameEncrypted  []byte
	BreederEmailEncrypted []byte
	PictureObjectKey      string
	Status                string
	CreatedAt             time.Time
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) error {
	_, err := q.db.Exec(ctx, createPet,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Species,
		arg.AgeYears,
		arg.Description,
		arg.BreederNameEncrypted,
		arg.BreederEmailEncrypted,
		arg.PictureObjectKey,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getPetByID = `-- name: GetPetByID :one
SELECT id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at FROM pets WHERE store_id = $1 AND id = $2
`

type GetPetByIDParams struct {
	StoreID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetPetByID(ctx context.Context, arg GetPetByIDParams) (Pet, error) {
	row := q.db.QueryRow(ctx, getPetByID, arg.StoreID, arg.ID)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.BreederNameEncrypted,
		&i.BreederEmailEncrypted,
		&i.PictureObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.SoldAt,
		&i.SoldByCustomerID,
		&i.RemovedAt,
	)
	return i, err
}

const getPetByIDUnscoped = `-- name: GetPetByIDUnscoped :one
SELECT id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at FROM pets WHERE id = $1
`

func (q *Queries) GetPetByIDUnscoped(ctx context.Context, id uuid.UUID) (Pet, error) {
	row := q.db.QueryRow(ctx, getPetByIDUnscoped, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.BreederNameEncrypted,
		&i.BreederEmailEncrypted,
		&i.PictureObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.SoldAt,
		&i.SoldByCustomerID,
		&i.RemovedAt,
	)
	return i, err
}

const listAvailableByStore = `-- name: ListAvailableByStore :many
SELECT id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at FROM pets
 WHERE store_id = $1
   AND status = 'AVAILABLE'
   AND ($2::pet_species IS NULL OR species = $2::pet_species)
   AND (
     created_at > $3
     OR (created_at = $3 AND id > $4)
   )
 ORDER BY created_at, id
 LIMIT $5
`

type ListAvailableByStoreParams struct {
	StoreID        uuid.UUID
	Species        *PetSpecies
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

func (q *Queries) ListAvailableByStore(ctx context.Context, arg ListAvailableByStoreParams) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listAvailableByStore,
		arg.StoreID,
		arg.Species,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Species,
			&i.AgeYears,
			&i.Description,
			&i.BreederNameEncrypted,
			&i.BreederEmailEncrypted,
			&i.PictureObjectKey,
			&i.Status,
			&i.CreatedAt,
			&i.SoldAt,
			&i.SoldByCustomerID,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoldByStore = `-- name: ListSoldByStore :many
SELECT id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at FROM pets
 WHERE store_id = $1
   AND status = 'SOLD'
   AND sold_at >= $2
   AND sold_at <= $3
   AND (
     sold_at > $4
     OR (sold_at = $4 AND id > $5)
   )
 ORDER BY sold_at, id
 LIMIT $6
`

type ListSoldByStoreParams struct {
	StoreID     uuid.UUID
	SoldFrom    pgtype.Timestamptz
	SoldTo      pgtype.Timestamptz
	AfterSoldAt pgtype.Timestamptz
	AfterID     uuid.UUID
	PageLimit   int32
}

func (q *Queries) ListSoldByStore(ctx context.Context, arg ListSoldByStoreParams) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listSoldByStore,
		arg.StoreID,
		arg.SoldFrom,
		arg.SoldTo,
		arg.AfterSoldAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Species,
			&i.AgeYears,
			&i.Description,
			&i.BreederNameEncrypted,
			&i.BreederEmailEncrypted,
			&i.PictureObjectKey,
			&i.Status,
			&i.CreatedAt,
			&i.SoldAt,
			&i.SoldByCustomerID,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPetsByIDs = `-- name: LockPetsByIDs :many
SELECT id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at FROM pets
 WHERE id = ANY($1::uuid[])
 ORDER BY id
   FOR UPDATE
`

func (q *Queries) LockPetsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Pet, error) {
	rows, err := q.db.Query(ctx, lockPetsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Species,
			&i.AgeYears,
			&i.Description,
			&i.BreederNameEncrypted,
			&i.BreederEmailEncrypted,
			&i.PictureObjectKey,
			&i.Status,
			&i.CreatedAt,
			&i.SoldAt,
			&i.SoldByCustomerID,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchasePet = `-- name: PurchasePet :one
UPDATE pets
   SET status = 'SOLD', sold_at = now(), sold_by_customer_id = $2
 WHERE id = $1 AND status = 'AVAILABLE'
RETURNING id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at
`

type PurchasePetParams struct {
	ID               uuid.UUID
	SoldByCustomerID pgtype.UUID
}

func (q *Queries) PurchasePet(ctx context.Context, arg PurchasePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, purchasePet, arg.ID, arg.SoldByCustomerID)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.BreederNameEncrypted,
		&i.BreederEmailEncrypted,
		&i.PictureObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.SoldAt,
		&i.SoldByCustomerID,
		&i.RemovedAt,
	)
	return i, err
}

const removePet = `-- name: RemovePet :one
UPDATE pets
   SET status = 'REMOVED', removed_at = now()
 WHERE id = $1 AND store_id = $2 AND status = 'AVAILABLE'
RETURNING id, store_id, name, species, age_years, description, breeder_name_encrypted, breeder_email_encrypted, picture_object_key, status, created_at, sold_at, sold_by_customer_id, removed_at
`

type RemovePetParams struct {
	ID      uuid.UUID
	StoreID uuid.UUID
}

func (q *Queries) RemovePet(ctx context.Context, arg RemovePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, removePet, arg.ID, arg.StoreID)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.BreederNameEncrypted,
		&i.BreederEmailEncrypted,
		&i.PictureObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.SoldAt,
		&i.SoldByCustomerID,
		&i.RemovedAt,
	)
	return i, err
}
