// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createStore = `-- name: CreateStore :exec
INSERT INTO stores (id, merchant_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateStoreParams struct {
	ID         uuid.UUID
	MerchantID uuid.UUID
	Name       string
	CreatedAt  time.Time
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) error {
	_, err := q.db.Exec(ctx, createStore,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, merchant_id, name, created_at FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getStoreByMerchantID = `-- name: GetStoreByMerchantID :one
SELECT id, merchant_id, name, created_at FROM stores WHERE merchant_id = $1
`

func (q *Queries) GetStoreByMerchantID(ctx context.Context, merchantID uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByMerchantID, merchantID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
