package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"roboticCrewChallenge/internal/app/listing"
	"roboticCrewChallenge/internal/auth"
	"roboticCrewChallenge/internal/domain"
	"roboticCrewChallenge/internal/graph/generated"
	"time"

	"github.com/google/uuid"
)

// CreatePet is the resolver for the createPet field.
func (r *mutationResolver) CreatePet(ctx context.Context, input generated.CreatePetInput) (*generated.Pet, error) {
	identity, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	pet, err := r.Listing.CreatePet(ctx, listing.CreatePetCommand{
		StoreID:      identity.StoreID,
		Name:         input.Name,
		Species:      string(input.Species),
		AgeYears:     input.AgeYears,
		Description:  input.Description,
		BreederName:  input.BreederName,
		BreederEmail: input.BreederEmail,
		Picture:      input.Picture.File,
	})
	if err != nil {
		return nil, err
	}
	return toGraphPet(pet), nil
}

// RemovePet is the resolver for the removePet field.
func (r *mutationResolver) RemovePet(ctx context.Context, id string) (*generated.Pet, error) {
	identity, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	petID, err := uuid.Parse(id)
	if err != nil {
		return nil, &domain.ValidationError{Field: "id", Msg: "is not a valid identifier"}
	}
	pet, err := r.Listing.RemovePet(ctx, identity.StoreID, petID)
	if err != nil {
		return nil, err
	}
	return toGraphPet(pet), nil
}

// PurchasePet is the resolver for the purchasePet field.
func (r *mutationResolver) PurchasePet(ctx context.Context, petID string) (*generated.PublicPet, error) {
	identity, err := auth.RequireCustomer(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(petID)
	if err != nil {
		return nil, &domain.ValidationError{Field: "petId", Msg: "is not a valid identifier"}
	}
	pet, err := r.Purchase.PurchasePet(ctx, identity.Subject, id)
	if err != nil {
		return nil, err
	}
	return toGraphPublicPet(pet), nil
}

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, petIds []string) ([]generated.PublicPet, error) {
	identity, err := auth.RequireCustomer(ctx)
	if err != nil {
		return nil, err
	}
	ids := make([]uuid.UUID, 0, len(petIds))
	for _, raw := range petIds {
		id, err := uuid.Parse(raw)
		if err != nil {
			return nil, &domain.ValidationError{Field: "petIds", Msg: "contains an invalid identifier"}
		}
		ids = append(ids, id)
	}
	pets, err := r.Purchase.Checkout(ctx, identity.Subject, ids)
	if err != nil {
		return nil, err
	}
	return toPublicPets(pets), nil
}

// PictureURL is the resolver for the pictureUrl field.
func (r *petResolver) PictureURL(ctx context.Context, obj *generated.Pet) (string, error) {
	return picturePath(obj.PictureObjectKey), nil
}

// PictureURL is the resolver for the pictureUrl field.
func (r *publicPetResolver) PictureURL(ctx context.Context, obj *generated.PublicPet) (string, error) {
	return picturePath(obj.PictureObjectKey), nil
}

// SoldPets is the resolver for the soldPets field.
func (r *queryResolver) SoldPets(ctx context.Context, from time.Time, to time.Time, first *int, after *string) (*generated.PetConnection, error) {
	identity, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	pets, nextCursor, err := r.Listing.SoldPets(ctx, identity.StoreID, from, to, clampFirst(first), cursorOrEmpty(after))
	if err != nil {
		return nil, err
	}
	return toConnection(pets, nextCursor, soldCursor), nil
}

// UnsoldPets is the resolver for the unsoldPets field.
func (r *queryResolver) UnsoldPets(ctx context.Context, first *int, after *string) (*generated.PetConnection, error) {
	identity, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	pets, nextCursor, err := r.Listing.UnsoldPets(ctx, identity.StoreID, clampFirst(first), cursorOrEmpty(after))
	if err != nil {
		return nil, err
	}
	return toConnection(pets, nextCursor, availableCursor), nil
}

// AvailablePets is the resolver for the availablePets field.
func (r *queryResolver) AvailablePets(ctx context.Context, storeID string, species *generated.Species, first *int, after *string) (*generated.PublicPetConnection, error) {
	if _, err := auth.RequireCustomer(ctx); err != nil {
		return nil, err
	}
	store, err := uuid.Parse(storeID)
	if err != nil {
		return nil, &domain.ValidationError{Field: "storeId", Msg: "is not a valid identifier"}
	}
	var speciesFilter *domain.Species
	if species != nil {
		s := domain.Species(*species)
		speciesFilter = &s
	}
	pets, nextCursor, err := r.Listing.AvailablePets(ctx, store, speciesFilter, clampFirst(first), cursorOrEmpty(after))
	if err != nil {
		return nil, err
	}
	return toPublicConnection(pets, nextCursor), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Pet returns generated.PetResolver implementation.
func (r *Resolver) Pet() generated.PetResolver { return &petResolver{r} }

// PublicPet returns generated.PublicPetResolver implementation.
func (r *Resolver) PublicPet() generated.PublicPetResolver { return &publicPetResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type petResolver struct{ *Resolver }
type publicPetResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
